### PR TITLE
NSClean demonstration for MOS, IFU

### PR DESCRIPTION
**Pull request by melanieclarke**
This PR adds two new notebooks for NIRSpec, demonstrating the use of NSClean for reducing 1/f noise in rate files.  MOS and IFU examples are included, with discussion of various methods of making background masks and the benefits and drawbacks the cleaning method.

### CODE REVIEW

**Comment by sosey** [comment]
@melanieclarke is there a second person on Nirspec that can be assigned as a reviewer? They should already have a github account and know basics of git and reviews.

**Comment by melanieclarke** [comment]
@sosey - @PatrickOgle says he can review, within a week or so.

**Review by sosey — CHANGES_REQUESTED** [review]
@melanieclarke will you add explicit information for the version of `jwst` that was used to test this notebook along with crds context?

**Comment by melanieclarke** [comment]
> @melanieclarke will you add explicit information for the version of `jwst` that was used to test this notebook along with crds context?

Will do, thanks for the suggestion.

**Review by sosey — APPROVED** [review]
LGTM - <edit> Hold up a sec, the environment is off ... ok, all good, merging

**Pull request merged**
